from __future__ import annotations

from typing import Any

ANALYSIS_JSON_SCHEMA: dict[str, Any] = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://aab-compare.local/schema/analysis-v3.json",
    "title": "AAB Compare analysis result",
    "type": "object",
    "required": [
        "schema_version",
        "mode",
        "aggregate",
        "config_snapshot",
        "dimensions",
        "left",
        "right",
        "warnings",
        "ownership",
        "diagnostics",
    ],
    "properties": {
        "schema_version": {"const": 3},
        "mode": {"enum": ["owned", "legacy"]},
        "aggregate": {"oneOf": [{"$ref": "#/$defs/aggregate"}, {"type": "null"}]},
        "config_snapshot": {"type": "object"},
        "dimensions": {
            "type": "object",
            "additionalProperties": {"$ref": "#/$defs/dimension"},
        },
        "left": {},
        "right": {},
        "warnings": {"type": "array", "items": {"type": "string"}},
        "ownership": {"type": "object"},
        "diagnostics": {"type": "object"},
    },
    "additionalProperties": False,
    "allOf": [
        {
            "if": {"properties": {"mode": {"const": "owned"}}},
            "then": {
                "properties": {
                    "aggregate": {"type": "null"},
                    "left": {"$ref": "#/$defs/owned_profile"},
                    "right": {"$ref": "#/$defs/owned_profile"},
                    "ownership": {"$ref": "#/$defs/ownership"},
                    "diagnostics": {"$ref": "#/$defs/owned_diagnostics"},
                    "dimensions": {
                        "required": [
                            "business_code",
                            "long_methods",
                            "images",
                            "resources",
                            "manifest",
                            "assets",
                        ],
                        "properties": {
                            "business_code": {"$ref": "#/$defs/dimension"},
                            "long_methods": {"$ref": "#/$defs/dimension"},
                            "images": {"$ref": "#/$defs/dimension"},
                            "resources": {"$ref": "#/$defs/dimension"},
                            "manifest": {"$ref": "#/$defs/dimension"},
                            "assets": {"$ref": "#/$defs/dimension"},
                        },
                        "additionalProperties": False,
                    },
                }
            },
            "else": {
                "properties": {
                    "aggregate": {"$ref": "#/$defs/aggregate"},
                    "left": {"$ref": "#/$defs/profile"},
                    "right": {"$ref": "#/$defs/profile"},
                    "dimensions": {
                        "required": [
                            "business_code",
                            "long_methods",
                            "manifest",
                            "resources",
                            "images",
                            "dependencies",
                            "assets_native",
                            "build_structure",
                        ],
                        "properties": {
                            "business_code": {"$ref": "#/$defs/dimension"},
                            "long_methods": {"$ref": "#/$defs/dimension"},
                            "manifest": {"$ref": "#/$defs/dimension"},
                            "resources": {"$ref": "#/$defs/dimension"},
                            "images": {"$ref": "#/$defs/dimension"},
                            "dependencies": {"$ref": "#/$defs/dimension"},
                            "assets_native": {"$ref": "#/$defs/dimension"},
                            "build_structure": {"$ref": "#/$defs/dimension"},
                        },
                        "additionalProperties": False,
                    },
                }
            },
        }
    ],
    "$defs": {
        "attribution": {
            "type": "object",
            "required": [
                "owned_source",
                "owned_generated",
                "heuristic_owned",
                "public_dependency",
                "tool_generated",
                "unresolved",
            ],
            "properties": {
                "owned_source": {"type": "integer", "minimum": 0},
                "owned_generated": {"type": "integer", "minimum": 0},
                "heuristic_owned": {"type": "integer", "minimum": 0},
                "public_dependency": {"type": "integer", "minimum": 0},
                "tool_generated": {"type": "integer", "minimum": 0},
                "unresolved": {"type": "integer", "minimum": 0},
            },
            "additionalProperties": False,
        },
        "ownership": {
            "type": "object",
            "required": ["strategy", "left", "right"],
            "properties": {
                "strategy": {"enum": ["strict_provenance", "heuristic_aab"]},
                "left": {"$ref": "#/$defs/attribution"},
                "right": {"$ref": "#/$defs/attribution"},
            },
            "additionalProperties": False,
        },
        "two_sided": {
            "type": "object",
            "required": ["left", "right"],
            "properties": {"left": {}, "right": {}},
            "additionalProperties": False,
        },
        "owned_diagnostics": {
            "type": "object",
            "required": [
                "dependencies",
                "native",
                "build_structure",
                "signing",
                "hardening",
                "agp",
                "projection",
                "resource_inventory",
                "selection",
            ],
            "properties": {
                "dependencies": {"$ref": "#/$defs/two_sided"},
                "native": {"$ref": "#/$defs/two_sided"},
                "build_structure": {"$ref": "#/$defs/two_sided"},
                "signing": {"$ref": "#/$defs/two_sided"},
                "hardening": {"$ref": "#/$defs/two_sided"},
                "agp": {"$ref": "#/$defs/two_sided"},
                "projection": {"$ref": "#/$defs/two_sided"},
                "resource_inventory": {"$ref": "#/$defs/two_sided"},
                "selection": {"$ref": "#/$defs/selection"},
            },
            "additionalProperties": False,
        },
        "selection": {
            "type": "object",
            "required": ["requested_mode", "registry_status", "message"],
            "properties": {
                "requested_mode": {"enum": ["auto", "owned", "heuristic"]},
                "registry_status": {
                    "enum": [
                        "not_provided",
                        "explicit_config",
                        "matched",
                        "missing",
                        "stale",
                        "invalid",
                    ]
                },
                "message": {"type": "string"},
            },
            "additionalProperties": False,
        },
        "aggregate": {
            "type": "object",
            "required": [
                "score",
                "minimum_score",
                "maximum_score",
                "analyzed_weight",
                "level",
            ],
            "properties": {
                "score": {"type": ["number", "null"]},
                "minimum_score": {"type": "number"},
                "maximum_score": {"type": "number"},
                "analyzed_weight": {"type": "integer", "minimum": 0, "maximum": 100},
                "level": {"type": ["string", "null"]},
            },
            "additionalProperties": False,
        },
        "profile": {
            "type": "object",
            "required": [
                "schema_version",
                "source_path",
                "sha256",
                "size",
                "modules",
                "counts",
                "files",
                "methods",
                "images",
                "manifests",
                "manifest_entries",
                "dependencies",
                "build_features",
                "warnings",
            ],
            "properties": {
                "schema_version": {"const": 1},
                "source_path": {"type": "string"},
                "sha256": {"type": "string", "pattern": "^[0-9a-f]{64}$"},
                "size": {"type": "integer", "minimum": 0},
                "modules": {"type": "array", "items": {"type": "string"}},
                "counts": {
                    "type": "object",
                    "additionalProperties": {"type": "integer", "minimum": 0},
                },
                "files": {"type": "array", "items": {"type": "object"}},
                "methods": {"type": "array", "items": {"type": "object"}},
                "images": {"type": "array", "items": {"type": "object"}},
                "manifests": {"type": "object"},
                "manifest_entries": {"type": "array", "items": {"type": "object"}},
                "dependencies": {"type": "array", "items": {"type": "string"}},
                "build_features": {"type": "array", "items": {"type": "string"}},
                "warnings": {"type": "array", "items": {"type": "string"}},
                "agp_version": {"type": ["string", "null"]},
                "duration_seconds": {"type": "number", "minimum": 0},
            },
        },
        "owned_profile": {
            "type": "object",
            "required": [
                "schema_version",
                "source_path",
                "sha256",
                "size",
                "modules",
                "counts",
                "files",
                "methods",
                "images",
                "manifests",
                "manifest_entries",
                "warnings",
            ],
            "properties": {
                "schema_version": {"const": 1},
                "source_path": {"type": "string"},
                "sha256": {"type": "string", "pattern": "^[0-9a-f]{64}$"},
                "size": {"type": "integer", "minimum": 0},
                "modules": {"type": "array", "items": {"type": "string"}},
                "counts": {
                    "type": "object",
                    "propertyNames": {"not": {"const": "native"}},
                    "additionalProperties": {"type": "integer", "minimum": 0},
                },
                "files": {"type": "array", "items": {"type": "object"}},
                "methods": {"type": "array", "items": {"type": "object"}},
                "images": {"type": "array", "items": {"type": "object"}},
                "manifests": {"type": "object"},
                "manifest_entries": {"type": "array", "items": {"type": "object"}},
                "warnings": {"type": "array", "items": {"type": "string"}},
            },
            "additionalProperties": False,
        },
        "dimension": {
            "type": "object",
            "required": [
                "key",
                "score",
                "left_coverage",
                "right_coverage",
                "confidence",
                "findings",
                "warnings",
                "metrics",
            ],
            "properties": {
                "key": {"type": "string"},
                "score": {"type": ["number", "null"]},
                "left_coverage": {"type": "number", "minimum": 0, "maximum": 1},
                "right_coverage": {"type": "number", "minimum": 0, "maximum": 1},
                "confidence": {"type": "number", "minimum": 0, "maximum": 1},
                "findings": {"type": "array", "items": {"type": "object"}},
                "warnings": {"type": "array", "items": {"type": "string"}},
                "metrics": {"type": "object"},
            },
            "additionalProperties": False,
        },
    },
}
